
#Settings
[settings]
	#If the front of the Tile Entities should face the player or should face outward
	facePlayer = false
	#Arms should render on sides when carrying
	renderArms = true

[modeloverrides]
	#Model Overrides based on NBT or on Meta. Advanced Users Only!
	overrides = [""]

